#virt-install --virt-type kvm --os-variant rhel10.0 --arch s390x --name rhel10.0-s390x --memory 8192 --location rhel-10.0-s390x-dvd.iso --disk path=./disk.qcow2,format=qcow2,bus=virtio,size=7 --initrd-inject=rhel10-dm-root-s390x.ks --nographics --extra-args "console=ttysclp0 inst.ks=file:/rhel10-dm-root-s390x.ks" --transient

# Generated by Anaconda 34.25.5.5
# Generated by pykickstart v3.32
#version=RHEL9
# Use text install
text
repo --name="AppStream" --baseurl=file:///run/install/sources/mount-0000-cdrom/AppStream

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

network --bootproto=dhcp --hostname=localhost.localdomain
firewall --disabled

# Use CDROM installation media
cdrom

# Root password. It will be reset by cloud-init
rootpw --allow-ssh redhat123

# Enable SELinux
selinux --enforcing

# System services
services --enabled="sshd,NetworkManager,cloud-init,cloud-init-local,cloud-config,cloud-final"

# System timezone
timezone Etc/UTC --utc

# Don't configure X
skipx

# Power down the machine after install, so that we can install right kernel
poweroff
#reboot

%pre --erroronfail
# Create GPT partition table with proper partition types for s390x
# Partition 1: /boot (1GB, Linux filesystem)
# Partition 2: / (rest of disk, Linux root s390x)
sfdisk --wipe always -X gpt /dev/vda << EOF
2048,2097152,0FC63DAF-8483-4772-8E79-3D69D8477DE4
,,5EEAD9A9-FE09-4A1E-A1D7-520D00531306
EOF
%end

%packages
@^minimal-environment
openssh-server
kernel
redhat-release

-*gpu-firmware*
-linux-firmware*
-iwl*

cloud-init
cloud-utils-growpart

NetworkManager

tpm2-tools
cryptsetup

# s390x specific packages
s390utils
s390utils-base

# Standard kernel for s390x (UKI may not be available)
kernel
kernel-modules
kernel-modules-extra

# versionlock plugin
python3-dnf-plugin-versionlock

# CoCo
afterburn
e2fsprogs

%end

# Run the Setup Agent on first boot
firstboot --disable

part /boot --onpart=vda1 --fstype=ext4
part / --onpart=vda2 --fstype=xfs

%post --erroronfail

# Install and configure zipl bootloader for s390x
echo "Configuring zipl bootloader..."

# Get the kernel version
KERNEL_VERSION=$(ls /boot/vmlinuz-* | sed 's/.*vmlinuz-//' | head -1)
ROOT_UUID=$(blkid -s UUID -o value /dev/vda2)

# Create zipl configuration
cat > /etc/zipl.conf << EOF
[defaultboot]
defaultauto
prompt=1
timeout=5
default=linux
target=/boot

[linux]
image=/boot/vmlinuz-${KERNEL_VERSION}
ramdisk=/boot/initramfs-${KERNEL_VERSION}.img
parameters="root=UUID=${ROOT_UUID} console=ttysclp0"
EOF

# Run zipl to install bootloader
zipl

# Cloud-init configuration for s390x
# Note: No WALinuxAgent for s390x, using cloud-init only

# Fstrim root
fstrim -v / ||:

%end